### Classification of text as postive or negative using sci-kit learn machine learning model


# Outlines
1. Data preparation 
2. Model selection
3. Analysis and evaluation
4. Improveing the model
5. Saving the model 

### Data set
Source: amazon.com, the amazon review as training data
full data source: http://jmcauley.ucsd.edu/data/amazon/

## Data processing
Open the data (Books_small.json) in sublime text and explore the data.
- The data is a json file and each line is another json object
- We can see the 'reviewText' in the data which is text content in the review
- another one is 'overall' in the data which is out of 5 star rating
- As these two field is important so we will take care of these


In [108]:
# creating enum class/regular class of programming (optional)
class Sentiment: #call the class Sentiment
    NEGATIVE ='NEGATIVE' # properties of the class
    NEUTRAL ='NEUTRAL'
    POSITIVE = 'POSITIVE'
    

# Making class review (it' much neater and helps keep track of things)
class Review: # call the class Review
    def __init__(self, text, score): # initialize with self (always) and our data fields
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
    
    #creating function withing review for getting setiment
    def get_sentiment(self): # all functions within a class pass in itself
        if self.score <= 2:
            #return 'NEGATIVE' 
            # This also works- we used Sentiment class just to be consistent with the string (so that not to float around/accidently take wrong thing)
            return Sentiment.NEGATIVE # refering this to sentiment class we created on top
        elif self.score == 3:
            #return 'NEUTRAL'
            return Sentiment.NEUTRAL
        else: # score of 4 or 5
            #return 'POSITIVE'
            return Sentiment.POSITIVE
        

In [5]:
# impor json library
import json
# loading data line by line
# First create file name
file_name = './sentiment/Books_small.json'

# open up the file with open
with open (file_name) as f:
    for line in f:
        print(line)
        break # here we get the raw text

{"reviewerID": "A1E5ZR1Z4OQJG", "asin": "1495329321", "reviewerName": "Pure Jonel \"Pure Jonel\"", "helpful": [0, 0], "reviewText": "Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters i

In [7]:
# now it wannna get the reviewText
with open (file_name) as f:
    for line in f:
        review =json.loads(line) # use json library to load line as review like dictionary
        print(review['reviewText'])
        print(review['overall'])
        break

Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters in this novel were also truly touching.Overall, this novel was fantastic.  I can&#8217;t wait to read more and to find out what happen

- So, we got all the things we need (two important fields out of json file)
- Now we gater all this in a nice way, we will get rid of this above code/statement

In [31]:
# Reading the file in more organized way (indexing of reviewText and score)
reviews = [] # create reviews empty list
with open (file_name) as f:
        for line in f:
            review =json.loads(line) # use json library to load line as review like dictionary
            reviews.append((review['reviewText'],review['overall'])) # append the reviews list and tuple objects of reviewText and a score
        # we used tuple here as we have two field/argument, becuase append takes only one argument, by using tuple we put two arguments
# check it it works (just put review number)
reviews[5]

('Love the book, great story line, keeps you entertained.for a first novel from this author she did a great job,  Would definitely recommend!',
 4.0)

In [16]:
# indexing to get reviewText and score (it works)
#reviews[5][0] # use 0 index to access text
reviews[5][1] # use 1 index to access score/overall rating

4.0

In [ ]:
- This is not yet the neatiest one
- As a data scientist, at some point the data get messy and it gets hard
  to parse through someone's code
- So, we gonna do real quick by making a data class for all data we loaded in

In [38]:
# now instead of appending tuple, create a Review object and pass in the text and the score 
reviews = [] # create reviews empty list
with open (file_name) as f:
    for line in f:
        review =json.loads(line) # use json library to load line as review like dictionary
        reviews.append(Review(review['reviewText'],review['overall'])) # instead of review, we used Review class that we created on top
         
# check it it works (just put review number)
reviews[5]

In [56]:
#reviews[5].text
reviews[5].score

4.0

- So, it is much neatier and helps keep tracking the things easily
- Now, we will initialize sentiment in our class, for adding sentiment class
- we need to create a function as above 

In [44]:
reviews[5].sentiment # works both way - without class sentiment

'POSITIVE'

In [45]:
reviews[5].sentiment # with class sentiment

'POSITIVE'

### Data processing /preparation
- Machine learning model does not love text data/ hard to read text data that we have
- Rather ML model loves matrices and numerical data as input (numerical vector)
- So, we need to convert the text data into quantative vector
- For that we will start with bag-of-words 

In [47]:
# check how many reviews we have in our data
len(reviews)

1000

In [49]:
# Splittting the data (1000 review) into train and test data set 
from sklearn.model_selection import train_test_split
# as we pass single review list, so we get two times output as training(or x)and test (or y)
training, test = train_test_split(reviews, test_size = 0.33, random_state=42 )

In [50]:
# cheking the split data
len(training), len(test)

(670, 330)

- now we will fit the bag-of-words model into the trainig set
- then we will build a classifer on that training set
- and we will test everyting on our test data

In [53]:
# printing the first text

print(training[0].text)
print(training[0].sentiment)

Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down.
POSITIVE


-Steps are:
- we will pass the data into bag-of-words vectorizer
- broadly, we will take the text and predict whether it is positive or negative
- so, the x would the text in our model and y the category/sentiment
- now split the training data into training x and train y and also test data

In [62]:
# splitting training data
train_x = [x.text for x in training] # to get text for x, apply list comprehension
train_y = [x.sentiment for x in training]

# splitting test data
test_x = [x.text for x in test] # for test our model we pass in test x
test_y = [x.sentiment for x in test] # to see if it matches up closley with test y

In [60]:
# checking first text for train_x
train_x[0]

"Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down."

In [61]:
# checking first setiment for train_y
train_y[0]

'POSITIVE'

### Bag of words vectorization 

In [64]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
# our corpus is train_x
vectorizer.fit_transform(train_x) # fit_transform method

# two steps of code: but perform same function as above (fit and tranform method)
#vectorizer.fit(x_train)
#train_x_vectors = vectorizer.transform(train_x)

<670x7372 sparse matrix of type '<class 'numpy.int64'>'
	with 41455 stored elements in Compressed Sparse Row format>

we get here sparse matrix with 670 training vlaues (documents), all of them 
have their own row and each one of those rows have 7372 columns

In [72]:
train_x_vectors = vectorizer.fit_transform(train_x) # apply both fit and transform to train_x

# numerical presentation of our test set text and we just do tranform here, as we don't fit a new model here
test_x_vectors = vectorizer.transform(test_x) # apply transform only to test_x


train_x_vectors[0] # print a matrix 

<1x7372 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [67]:
train_x[0] # print just piece of text

"Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down."

In [68]:
print(train_x[0])
print(train_x_vectors[0]) # print a matrix that represemt the text so it counts all position that are nonzero in our matrix

Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down.
  (0, 7086)	1
  (0, 1148)	1
  (0, 350)	2
  (0, 1800)	1
  (0, 6595)	1
  (0, 562)	1
  (0, 3054)	1
  (0, 1558)	1
  (0, 6475)	1
  (0, 6593)	1
  (0, 2895)	1
  (0, 7353)	1
  (0, 539)	1
  (0, 1515)	1
  (0, 5197)	1
  (0, 3545)	1
  (0, 2007)	1


In [71]:
# let's look the matrix in more tradional way
print(train_x[0])
print(train_x_vectors[0].toarray())

Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down.
[[0 0 0 ... 0 0 0]]


- so our final data for building the model is
 - train_x_vectors and train_y

In [81]:
# final data for building the model (we will fit a model around these two)
#train_x_vectors
#train_y

### Classification 

- Choosing the right model
- we have no x and y, so let's do some classficiation 
- There are many models, let's take coiple of models and check how they perform
- or part of test any model: train model, run it on test data seeing what performs better

#### Linear SVM Classifier

In [82]:
#from sklearn.svm import SVC
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x_vectors, train_y) # pass in x and y to fit this classifier to our data

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [84]:
# now predict something (based on training SVM classifier)
test_x[0] # it looks like positive review
# let's get vector for that
test_x_vectors[0]

<1x7372 sparse matrix of type '<class 'numpy.int64'>'
	with 36 stored elements in Compressed Sparse Row format>

In [85]:
# let's predict wheter this text test_X[0] is positive or negative
clf_svm.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

#### Decision Tree Classifer 

In [87]:
from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()
clf_dec.fit(train_x_vectors, train_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [88]:
clf_dec.predict(test_x_vectors[0]) # This also predicts positive

array(['POSITIVE'], dtype='<U8')

#### Naive Bayes Classifier

In [95]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = GaussianNB()
clf_gnb.fit(train_x_vectors.toarray(), train_y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [99]:
clf_gnb.predict(test_x_vectors.toarray())[0]

'POSITIVE'

#### Logistic Regression

In [93]:
from sklearn.tree import DecisionTreeClassifier
clf_log = DecisionTreeClassifier()
clf_log.fit(train_x_vectors, train_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [94]:
clf_log.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

All the classifiers predicted psoitive for the first test set, so look pretty goods initially

### Evaluation

In [103]:
# let's look entire test set and see how accurately we predict every one of those test examples
# Mean Accuracy on all test labels (how many lables are actually predicted correctly)
print(clf_svm.score(test_x_vectors, test_y)) # comapre prediction of test_x_vector to our actual testy_y
print(clf_dec.score(test_x_vectors, test_y))
print(clf_gnb.score(test_x_vectors.toarray(), test_y))
print(clf_log.score(test_x_vectors, test_y))

0.8242424242424242
0.7787878787878788
0.8121212121212121
0.7393939393939394


In [109]:
# More important metric (recommended for data scientist)
# F1 score
from sklearn.metrics import f1_score

f1_score(test_y,clf_svm.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE, Sentiment.NEUTRAL])

array([0.91319444, 0.22222222, 0.21052632])

Here we see, f1 score as 91% postitive, but it is pretty trash for netural 
and negative labels, so we can improve the model further (we look for the model that equally predict for all categories). Let's check 
for the other model...

In [111]:
f1_score(test_y,clf_dec.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE, Sentiment.NEUTRAL])

array([0.87804878, 0.06896552, 0.14035088])

In [114]:
f1_score(test_y,clf_gnb.predict(test_x_vectors.toarray()), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE, Sentiment.NEUTRAL])

array([0.89678511, 0.09090909, 0.08510638])

In [115]:
f1_score(test_y,clf_log.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE, Sentiment.NEUTRAL])

array([0.85612789, 0.        , 0.0952381 ])

In [118]:
# How could we imporve the model acuracy
# As all the classfier predicted well for positive, so there is no issue with modeling
# So, let's look at the data, if we can  improve the model

train_y[0:5]

['POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE']

In [119]:
# counting how many actual positive labels we have
train_y.count(Sentiment.POSITIVE)
# we had 670 train lables in total

552

So right away, our models are gonna be heavily biased towards these positive lables as there's way more of them.

In [120]:
# counting how many actual negative labels we have
train_y.count(Sentiment.NEGATIVE)

47

In [121]:
# rest of the review would be neutral
# counting how many actual neturallabels we have
train_y.count(Sentiment.NEUTRAL)

71

So, we got our issue for bad f1 score, we need to balace our negative and postive data.
The way to do this is adding more data. Let's work with 10000 files !

## Saving model

In [124]:
# saving model with a library called pickle
# we need to save the model so that we can use it later and avoid retraining the model
import pickle

with open('./sentiment/sentiment_classifer_1000_samples.pkl', 'wb') as f:
    pickle.dump(clf_svm, f)
